### ISSUE TITLE
exampleSite ist missing

### ISSUE THREAD

**Issue by mluethi** [JesseZhuang/hugo-material-blog#1]
I'm new to Hugo but I want to use it for my own blog. I really like your theme, but I'm not sure how to use it. Can you create a exampleSite with some content in it?
Thank you very much in advance!

**Comment by JesseZhuang** [comment]
Thank you for your interest. I have added an example site with article and page templates, and config toml file. Let me know if you have any questions. I will consider the issue closed after two weeks.
